services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - infrastructure_net
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/traefik/etc/localtime:/etc/localtime:ro
      - ${DOCKER_ROOT}/traefik/traefik.yml:/traefik.yml:ro
      - ${DOCKER_ROOT}/traefik/acme.json:/acme.json
      - ${DOCKER_ROOT}/traefik/dynamic.yml:/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik:/var/log/traefik
    labels:
      - glance.name=traefik
      - glance.icon=mdi:router-network
      - glance.url=https://${DASHBOARD_DOMAIN}/
      - glance.description=Routing Management
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.dashboard.rule=Host(`${DASHBOARD_DOMAIN}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=myresolver
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=crowdsec,traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH_CREDENTIALS}
      - traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.enabled=true
      - traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecLapiHost=crowdsec:8080
      - traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecLapiKey=${CROWDSEC_API_KEY}
      - traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecMode=live
      - traefik.http.routers.dashboard.tls.domains[0].main=${ROOT_DOMAIN}
      - traefik.http.routers.dashboard.tls.domains[0].sans=*.${ROOT_DOMAIN}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - proxy
      - infrastructure_net
    environment:
      - TZ=${TZ}
      - GID=${GID}
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios
    volumes:
      - ${DOCKER_ROOT}/crowdsec/config:/etc/crowdsec
      - ${DOCKER_ROOT}/crowdsec/data:/var/lib/crowdsec/data
      - /var/log/traefik:/var/log/traefik:ro
    labels:
      - glance.name=Crowdsec
      - glance.icon=mdi:security
      - glance.description=Security Management
      - glance.parent=traefik
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    networks:
      - infrastructure_net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 4000:4000
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/blocky/config.yml:/app/config.yml
    labels:
      - glance.name=Blocky
      - glance.icon=mdi:shield-check
      - glance.description=DNS Ad-blocking

networks:
  proxy:
    external: true
  infrastructure_net:
    external: true
